sudo: required
services:
  - docker

before_install:
  - docker build -t adityayadav/react-test -f ./client/Dockerfile.dev ./client
#  - docker build myotherproject

script:
  -  docker run -e CI=true adityayadav/react-test npm test

after_success:
  - docker build -t adityayadav/multi-client ./client
  - docker build -t adityayadav/multi-client ./nginx
  - docker build -t adityayadav/multi-client ./server
  - docker build -t adityayadav/multi-client ./worker

  #log in to docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those image and push to docker hub

<<<<<<< HEAD
  -docker push adityayadav/multi-client
  -docker push adityayadav/multi-nginx
  -docker push adityayadav/multi-server
  -docker push adityayadav/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-744976051710
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
=======
  - docker push adityayadav/multi-client
  - docker push adityayadav/multi-nginx
  - docker push adityayadav/multi-server
  - docker push adityayadav/multi-worker
>>>>>>> e06bbb107937c8b738076e500134dc28e73dbd41
